//
// Generated by Bluespec Compiler, version 2022.01-29-gc526ff54 (build c526ff54)
//
// On Thu Oct 27 01:56:17 CST 2022
//
//
// Ports:
// Name                         I/O  size props
// RDY_alu_set                    O     1 const
// alu_out_to_reg                 O    38 reg
// RDY_alu_out_to_reg             O     1 const
// alu_out_to_mem                 O    98 reg
// RDY_alu_out_to_mem             O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// alu_set_alu_in                 I   237
// EN_alu_set                     I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkISAEX(CLK,
	       RST_N,

	       alu_set_alu_in,
	       EN_alu_set,
	       RDY_alu_set,

	       alu_out_to_reg,
	       RDY_alu_out_to_reg,

	       alu_out_to_mem,
	       RDY_alu_out_to_mem);
  input  CLK;
  input  RST_N;

  // action method alu_set
  input  [236 : 0] alu_set_alu_in;
  input  EN_alu_set;
  output RDY_alu_set;

  // value method alu_out_to_reg
  output [37 : 0] alu_out_to_reg;
  output RDY_alu_out_to_reg;

  // value method alu_out_to_mem
  output [97 : 0] alu_out_to_mem;
  output RDY_alu_out_to_mem;

  // signals for module outputs
  wire [97 : 0] alu_out_to_mem;
  wire [37 : 0] alu_out_to_reg;
  wire RDY_alu_out_to_mem, RDY_alu_out_to_reg, RDY_alu_set;

  // register alu_out_to_memx
  reg [97 : 0] alu_out_to_memx;
  wire [97 : 0] alu_out_to_memx$D_IN;
  wire alu_out_to_memx$EN;

  // register alu_out_to_regx
  reg [37 : 0] alu_out_to_regx;
  wire [37 : 0] alu_out_to_regx$D_IN;
  wire alu_out_to_regx$EN;

  // remaining internal signals
  reg [31 : 0] CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_IF_ETC__q9,
	       CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_i_ETC__q8,
	       CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7,
	       CASE_alu_set_alu_in_BITS_219_TO_217_0b0_SEXT_a_ETC__q5,
	       CASE_alu_set_alu_in_BITS_236_TO_230_0b0_alu_se_ETC__q6,
	       IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36;
  reg [4 : 0] CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_s_ETC__q11;
  reg CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_al_ETC__q10;
  wire [127 : 0] SEXT_NEG_alu_inx_wget_BITS_172_TO_141_8_9_MUL__ETC___d50,
		 SEXT_alu_inx_wget_BITS_172_TO_141__0_MUL_SEXT__ETC___d43;
  wire [63 : 0] SEXT_alu_inx_wget_BITS_140_TO_109_1___d42,
		SEXT_alu_inx_wget_BITS_172_TO_141____d40;
  wire [31 : 0] IF_alu_inx_wget_BITS_236_TO_230_8_EQ_0b1_9_THE_ETC___d80,
		NEG_alu_set_alu_in_BITS_172_TO_141__q4,
		SEXT_alu_inx_wget_BITS_236_TO_225____d9,
		alu_inx_wget_BITS_172_TO_141_PLUS_SEXT_alu_inx_ETC___d10,
		alu_set_alu_in_BITS_140_TO_109__q3,
		alu_set_alu_in_BITS_172_TO_141__q2;
  wire [11 : 0] alu_set_alu_in_BITS_236_TO_225__q1;

  // action method alu_set
  assign RDY_alu_set = 1'd1 ;

  // value method alu_out_to_reg
  assign alu_out_to_reg = alu_out_to_regx ;
  assign RDY_alu_out_to_reg = 1'd1 ;

  // value method alu_out_to_mem
  assign alu_out_to_mem = alu_out_to_memx ;
  assign RDY_alu_out_to_mem = 1'd1 ;

  // register alu_out_to_memx
  assign alu_out_to_memx$D_IN =
	     { CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_i_ETC__q8,
	       65'd0,
	       alu_set_alu_in[211:205] == 7'b0000011 } ;
  assign alu_out_to_memx$EN = EN_alu_set ;

  // register alu_out_to_regx
  assign alu_out_to_regx$D_IN =
	     { CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_IF_ETC__q9,
	       CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_al_ETC__q10,
	       CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_s_ETC__q11 } ;
  assign alu_out_to_regx$EN = EN_alu_set ;

  // remaining internal signals
  assign IF_alu_inx_wget_BITS_236_TO_230_8_EQ_0b1_9_THE_ETC___d80 =
	     (alu_set_alu_in[236:230] == 7'b0000001) ?
	       CASE_alu_set_alu_in_BITS_219_TO_217_0b0_SEXT_a_ETC__q5 :
	       CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 ;
  assign NEG_alu_set_alu_in_BITS_172_TO_141__q4 = -alu_set_alu_in[172:141] ;
  assign SEXT_NEG_alu_inx_wget_BITS_172_TO_141_8_9_MUL__ETC___d50 =
	     { {32{NEG_alu_set_alu_in_BITS_172_TO_141__q4[31]}},
	       NEG_alu_set_alu_in_BITS_172_TO_141__q4 } *
	     SEXT_alu_inx_wget_BITS_140_TO_109_1___d42 ;
  assign SEXT_alu_inx_wget_BITS_140_TO_109_1___d42 =
	     { {32{alu_set_alu_in_BITS_140_TO_109__q3[31]}},
	       alu_set_alu_in_BITS_140_TO_109__q3 } ;
  assign SEXT_alu_inx_wget_BITS_172_TO_141__0_MUL_SEXT__ETC___d43 =
	     SEXT_alu_inx_wget_BITS_172_TO_141____d40 *
	     SEXT_alu_inx_wget_BITS_140_TO_109_1___d42 ;
  assign SEXT_alu_inx_wget_BITS_172_TO_141____d40 =
	     { {32{alu_set_alu_in_BITS_172_TO_141__q2[31]}},
	       alu_set_alu_in_BITS_172_TO_141__q2 } ;
  assign SEXT_alu_inx_wget_BITS_236_TO_225____d9 =
	     { {20{alu_set_alu_in_BITS_236_TO_225__q1[11]}},
	       alu_set_alu_in_BITS_236_TO_225__q1 } ;
  assign alu_inx_wget_BITS_172_TO_141_PLUS_SEXT_alu_inx_ETC___d10 =
	     alu_set_alu_in[172:141] +
	     SEXT_alu_inx_wget_BITS_236_TO_225____d9 ;
  assign alu_set_alu_in_BITS_140_TO_109__q3 = alu_set_alu_in[140:109] ;
  assign alu_set_alu_in_BITS_172_TO_141__q2 = alu_set_alu_in[172:141] ;
  assign alu_set_alu_in_BITS_236_TO_225__q1 = alu_set_alu_in[236:225] ;
  always@(alu_set_alu_in or
	  alu_inx_wget_BITS_172_TO_141_PLUS_SEXT_alu_inx_ETC___d10 or
	  SEXT_alu_inx_wget_BITS_236_TO_225____d9 or
	  alu_set_alu_in_BITS_172_TO_141__q2)
  begin
    case (alu_set_alu_in[219:217])
      3'b0:
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 =
	      alu_inx_wget_BITS_172_TO_141_PLUS_SEXT_alu_inx_ETC___d10;
      3'b001:
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 =
	      alu_set_alu_in[172:141] <<
	      SEXT_alu_inx_wget_BITS_236_TO_225____d9;
      3'b010:
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 =
	      { 31'b0,
		(alu_set_alu_in[172:141] ^ 32'h80000000) <
		(SEXT_alu_inx_wget_BITS_236_TO_225____d9 ^ 32'h80000000) };
      3'b011:
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 =
	      { 31'b0,
		alu_set_alu_in[172:141] <
		SEXT_alu_inx_wget_BITS_236_TO_225____d9 };
      3'b100:
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 =
	      alu_set_alu_in[172:141] ^
	      SEXT_alu_inx_wget_BITS_236_TO_225____d9;
      3'b101:
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 =
	      alu_set_alu_in[172:141] >>
	      SEXT_alu_inx_wget_BITS_236_TO_225____d9 |
	      ~(32'hFFFFFFFF >> SEXT_alu_inx_wget_BITS_236_TO_225____d9) &
	      {32{alu_set_alu_in_BITS_172_TO_141__q2[31]}};
      3'b110:
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 =
	      alu_set_alu_in[172:141] |
	      SEXT_alu_inx_wget_BITS_236_TO_225____d9;
      3'b111:
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 =
	      alu_set_alu_in[172:141] &
	      SEXT_alu_inx_wget_BITS_236_TO_225____d9;
    endcase
  end
  always@(alu_set_alu_in or
	  SEXT_alu_inx_wget_BITS_172_TO_141__0_MUL_SEXT__ETC___d43 or
	  SEXT_alu_inx_wget_BITS_172_TO_141____d40 or
	  SEXT_NEG_alu_inx_wget_BITS_172_TO_141_8_9_MUL__ETC___d50)
  begin
    case (alu_set_alu_in[219:217])
      3'b0:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_SEXT_a_ETC__q5 =
	      SEXT_alu_inx_wget_BITS_172_TO_141__0_MUL_SEXT__ETC___d43[31:0];
      3'b001, 3'b011:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_SEXT_a_ETC__q5 =
	      SEXT_alu_inx_wget_BITS_172_TO_141__0_MUL_SEXT__ETC___d43[63:32];
      3'b010:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_SEXT_a_ETC__q5 =
	      SEXT_alu_inx_wget_BITS_172_TO_141____d40[31] ?
		SEXT_NEG_alu_inx_wget_BITS_172_TO_141_8_9_MUL__ETC___d50[63:32] :
		SEXT_alu_inx_wget_BITS_172_TO_141__0_MUL_SEXT__ETC___d43[63:32];
      default: CASE_alu_set_alu_in_BITS_219_TO_217_0b0_SEXT_a_ETC__q5 = 32'd0;
    endcase
  end
  always@(alu_set_alu_in)
  begin
    case (alu_set_alu_in[236:230])
      7'b0:
	  CASE_alu_set_alu_in_BITS_236_TO_230_0b0_alu_se_ETC__q6 =
	      alu_set_alu_in[172:141] + alu_set_alu_in[140:109];
      7'b0100000:
	  CASE_alu_set_alu_in_BITS_236_TO_230_0b0_alu_se_ETC__q6 =
	      alu_set_alu_in[172:141] - alu_set_alu_in[140:109];
      default: CASE_alu_set_alu_in_BITS_236_TO_230_0b0_alu_se_ETC__q6 = 32'd0;
    endcase
  end
  always@(alu_set_alu_in or
	  CASE_alu_set_alu_in_BITS_236_TO_230_0b0_alu_se_ETC__q6 or
	  alu_set_alu_in_BITS_172_TO_141__q2)
  begin
    case (alu_set_alu_in[219:217])
      3'b0:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 =
	      CASE_alu_set_alu_in_BITS_236_TO_230_0b0_alu_se_ETC__q6;
      3'b001:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 =
	      alu_set_alu_in[172:141] << alu_set_alu_in[113:109];
      3'b010:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 =
	      { 31'b0,
		(alu_set_alu_in[172:141] ^ 32'h80000000) <
		(alu_set_alu_in[140:109] ^ 32'h80000000) };
      3'b011:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 =
	      { 31'b0, alu_set_alu_in[172:141] < alu_set_alu_in[140:109] };
      3'b100:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 =
	      alu_set_alu_in[172:141] ^ alu_set_alu_in[140:109];
      3'b101:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 =
	      alu_set_alu_in[172:141] >> alu_set_alu_in[113:109] |
	      ~(32'hFFFFFFFF >> alu_set_alu_in[113:109]) &
	      {32{alu_set_alu_in_BITS_172_TO_141__q2[31]}};
      3'b110:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 =
	      alu_set_alu_in[172:141] | alu_set_alu_in[140:109];
      3'b111:
	  CASE_alu_set_alu_in_BITS_219_TO_217_0b0_CASE_a_ETC__q7 =
	      alu_set_alu_in[172:141] & alu_set_alu_in[140:109];
    endcase
  end
  always@(alu_set_alu_in or
	  alu_inx_wget_BITS_172_TO_141_PLUS_SEXT_alu_inx_ETC___d10)
  begin
    case (alu_set_alu_in[211:205])
      7'b0000011:
	  CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_i_ETC__q8 =
	      alu_inx_wget_BITS_172_TO_141_PLUS_SEXT_alu_inx_ETC___d10;
      7'b0010011, 7'b0110011:
	  CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_i_ETC__q8 = 32'd0;
      default: CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_i_ETC__q8 = 32'd0;
    endcase
  end
  always@(alu_set_alu_in or
	  IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36 or
	  IF_alu_inx_wget_BITS_236_TO_230_8_EQ_0b1_9_THE_ETC___d80)
  begin
    case (alu_set_alu_in[211:205])
      7'b0010011:
	  CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_IF_ETC__q9 =
	      IF_alu_inx_wget_BITS_219_TO_217_EQ_0b0_THEN_al_ETC___d36;
      7'b0110011:
	  CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_IF_ETC__q9 =
	      IF_alu_inx_wget_BITS_236_TO_230_8_EQ_0b1_9_THE_ETC___d80;
      default: CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_IF_ETC__q9 = 32'd0;
    endcase
  end
  always@(alu_set_alu_in)
  begin
    case (alu_set_alu_in[211:205])
      7'b0010011, 7'b0110011:
	  CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_al_ETC__q10 =
	      alu_set_alu_in[108];
      default: CASE_alu_set_alu_in_BITS_211_TO_205_0b10011_al_ETC__q10 =
		   alu_set_alu_in[211:205] == 7'b0000011 &&
		   alu_set_alu_in[108];
    endcase
  end
  always@(alu_set_alu_in)
  begin
    case (alu_set_alu_in[211:205])
      7'b0000011, 7'b0010011, 7'b0110011:
	  CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_s_ETC__q11 =
	      alu_set_alu_in[216:212];
      default: CASE_alu_set_alu_in_BITS_211_TO_205_0b11_alu_s_ETC__q11 = 5'd0;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        alu_out_to_memx <= `BSV_ASSIGNMENT_DELAY 98'd0;
	alu_out_to_regx <= `BSV_ASSIGNMENT_DELAY 38'd0;
      end
    else
      begin
        if (alu_out_to_memx$EN)
	  alu_out_to_memx <= `BSV_ASSIGNMENT_DELAY alu_out_to_memx$D_IN;
	if (alu_out_to_regx$EN)
	  alu_out_to_regx <= `BSV_ASSIGNMENT_DELAY alu_out_to_regx$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    alu_out_to_memx = 98'h2AAAAAAAAAAAAAAAAAAAAAAAA;
    alu_out_to_regx = 38'h2AAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_alu_set) $display("%d", alu_out_to_regx[31:0]);
  end
  // synopsys translate_on
endmodule  // mkISAEX

